const {app,BrowserWindow,ipcMain,dialog,net,shell}=require('electron');const path=require('node:path');const fs=require('node:fs/promises');const {execFile}=require('node:child_process');const os=require('node:os');
let win;const office='alexander.rippke@gustav-schmidt.de';
app.disableHardwareAcceleration();
const logFile=()=>path.join(app.getPath('userData'),'diagnose.log');
function diagnose(text){require('node:fs').mkdirSync(app.getPath('userData'),{recursive:true});require('node:fs').appendFileSync(logFile(),new Date().toISOString()+' '+text+'\n')}
process.on('uncaughtException',error=>{diagnose('MAIN_ERROR '+error.name+' '+error.message);dialog.showErrorBox('Montagebericht – Fehler','Ein Fehler ist aufgetreten. Bitte die App neu starten. Diagnose: '+logFile())});
process.on('unhandledRejection',error=>diagnose('REJECTION '+String(error?.message||error)));
app.on('child-process-gone',(_event,details)=>diagnose('PROCESS '+details.type+' '+details.reason+' '+details.exitCode));
app.on('web-contents-created',(_event,contents)=>contents.on('render-process-gone',(_e,details)=>{diagnose('RENDER '+details.reason+' '+details.exitCode);dialog.showErrorBox('Montagebericht – Fensterfehler','Das App-Fenster wurde beendet. Bitte neu starten. Diagnose: '+logFile())}));
ipcMain.handle('read-calendar',async(event,range)=>{validateSender(event);if(!range||!/^\d{4}-\d{2}-\d{2}$/.test(range.start)||!/^\d{4}-\d{2}-\d{2}$/.test(range.end))return {ok:false,message:'Bitte einen gültigen Zeitraum auswählen.'};if(!['Kalender','Iris Illian'].includes(range.calendar))return {ok:false,message:'Ungültiger Kalender.'};const script=await fs.readFile(path.join(__dirname,'outlook-calendar.ps1'),'utf8');return new Promise(resolve=>execFile('powershell.exe',['-NoProfile','-NonInteractive','-Command','& {'+script+'} -StartDate $env:MONTAGE_START -EndDate $env:MONTAGE_END -CalendarName $env:MONTAGE_CALENDAR'],{env:{...process.env,MONTAGE_START:range.start,MONTAGE_END:range.end,MONTAGE_CALENDAR:range.calendar},windowsHide:true,timeout:60000,maxBuffer:4*1024*1024,encoding:'utf8'},(error,stdout)=>{try{const result=JSON.parse(stdout.replace(/^\uFEFF/,'').trim());resolve(result)}catch{resolve({ok:false,message:'Kalender konnte nicht gelesen werden. Bitte klassisches Outlook mit dem gewählten Kalender öffnen.'})}}))});
async function renderPdf(){await win.webContents.executeJavaScript('preparePrint()');return win.webContents.printToPDF({printBackground:true,preferCSSPageSize:true,displayHeaderFooter:false})}
function validateSender(event){if(event.sender!==win.webContents)throw Error('Ungültiges Fenster')}
app.whenReady().then(()=>{win=new BrowserWindow({width:1250,height:900,minWidth:760,minHeight:600,title:'Montagebericht · Gustav Schmidt',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());win.webContents.on('will-prevent-unload',event=>{const choice=dialog.showMessageBoxSync(win,{type:'warning',buttons:['Weiter bearbeiten','Trotzdem schließen'],defaultId:0,cancelId:0,message:'Berichte enthalten ungespeicherte Änderungen.',detail:'Zum Sichern als Berichtsdatei bitte weiter bearbeiten und jeden markierten Tab speichern. Die lokale Sitzung wird beim nächsten Start wiederhergestellt.'});if(choice===1)event.preventDefault()});win.loadFile(path.join(__dirname,'ui/index.html'))});app.on('window-all-closed',()=>app.quit());
ipcMain.handle('save-pdf',async event=>{validateSender(event);const result=await dialog.showSaveDialog(win,{title:'Montagebericht als PDF speichern',defaultPath:'Montagebericht.pdf',filters:[{name:'PDF',extensions:['pdf']}]});if(result.canceled)return {canceled:true};try{await fs.writeFile(result.filePath,await makePdf());return {ok:true}}catch{return {ok:false,message:'PDF konnte nicht gespeichert werden.'}}});
ipcMain.handle('outlook-draft',async(event,data)=>{validateSender(event);if(!data||typeof data.officeEmail!=='string'||! /^[^\s@;,]+@[^\s@;,]+\.[^\s@;,]+$/.test(data.officeEmail)||data.officeEmail.length>254)return {ok:false,message:'Bitte einen gültigen Büro-Empfänger auswählen.'};if(!data||typeof data.email!=='string'||! /^[^\s@;,]+@[^\s@;,]+\.[^\s@;,]+$/.test(data.email)||data.email.length>254)return {ok:false,message:'Bitte eine gültige Kunden-E-Mail eintragen.'};if(typeof data.customer!=='string'||typeof data.order!=='string'||!data.customer.trim()||!data.order.trim())return {ok:false,message:'Bitte Kunde und Auftragsnummer ergänzen.'};const folder=path.join(app.getPath('documents'),'Montageberichte');await fs.mkdir(folder,{recursive:true});const pdf=path.join(folder,'Montagebericht-'+Date.now()+'.pdf');let temp;try{await fs.writeFile(pdf,await makePdf());temp=await fs.mkdtemp(path.join(os.tmpdir(),'montagebericht-'));const file=path.join(temp,'draft.json');await fs.writeFile(file,JSON.stringify({to:[data.officeEmail,data.email].filter((x,i,a)=>a.indexOf(x)===i).join(';'),subject:('Montagebericht – '+data.customer+' – Auftrag '+data.order).slice(0,250).replace(/[\r\n]/g,' '),body:'Guten Tag,\r\n\r\nanbei erhalten Sie den Montagebericht zu Auftrag '+data.order+'.',pdf}));const draftScript=await fs.readFile(path.join(__dirname,'outlook-draft.ps1'),'utf8');await new Promise((resolve,reject)=>execFile('powershell.exe',['-NoProfile','-NonInteractive','-Command','& {'+draftScript+'} -DataFile $env:MONTAGE_DATA'],{env:{...process.env,MONTAGE_DATA:file},windowsHide:true,timeout:60000},(error,stdout)=>error||!stdout.includes('DRAFT_READY')?reject(error||Error('Outlook')):resolve()));return {ok:true,message:'Outlook-Entwurf mit PDF geöffnet. Bitte Absender und Empfänger prüfen und in Outlook senden.'}}catch{return {ok:false,message:'PDF wurde unter Dokumente / Montageberichte gespeichert. Ein Entwurf mit Anhang benötigt klassisches Outlook mit eingerichtetem Postfach.'}}finally{if(temp)await fs.rm(temp,{recursive:true,force:true})}});

const crypto=require('node:crypto');
function archiveFolder(){return path.join(app.getPath('documents'),'Montageberichte','Abgeschlossen')}
async function archivedPdf(id){if(!/^[0-9a-f-]{36}$/.test(id))throw Error('Ungültige Bericht-ID');const dir=path.join(archiveFolder(),id);const record=JSON.parse(await fs.readFile(path.join(dir,'nachweis.json'),'utf8'));const pdf=await fs.readFile(path.join(dir,'bericht.pdf'));if(crypto.createHash('sha256').update(pdf).digest('hex')!==record.pdfSha256)throw Error('Archiv-PDF wurde verändert');return pdf}
async function makePdf(){const data=await win.webContents.executeJavaScript('snapshot()');if(data.fields.finalizedId&&data.archive){const pdf=Buffer.from(data.archive.pdf,'base64');if(crypto.createHash('sha256').update(pdf).digest('hex')!==data.archive.sha256)throw Error('Archiv-PDF wurde verändert');return pdf}return data.fields.finalizedId?archivedPdf(data.fields.finalizedId):renderPdf()}
ipcMain.handle('finalize-report',async event=>{validateSender(event);let dir;try{const data=await win.webContents.executeJavaScript('snapshot()');if(!data.signature||!data.fields.signer?.trim()||!data.fields.signatureAccepted)throw Error('Kundenbestätigung fehlt');if(!/^[0-9a-f-]{36}$/.test(data.fields.finalizedId))throw Error('Bericht-ID fehlt');await fs.mkdir(archiveFolder(),{recursive:true});dir=path.join(archiveFolder(),data.fields.finalizedId);await fs.mkdir(dir);const pdf=await renderPdf();await fs.writeFile(path.join(dir,'bericht.pdf'),pdf,{flag:'wx'});await fs.writeFile(path.join(dir,'nachweis.json'),JSON.stringify({schema:1,archivedAt:new Date().toISOString(),pdfSha256:crypto.createHash('sha256').update(pdf).digest('hex'),snapshot:data},null,2),{flag:'wx'});return {ok:true,path:dir}}catch(error){return {ok:false,message:'Abschluss konnte nicht gespeichert werden: '+error.message}}});


ipcMain.handle('reload-report',event=>{validateSender(event);win.webContents.reload();return {ok:true}});

const {releaseInfo}=require('./updates.cjs');let checkedUpdate=null;
ipcMain.handle('check-update',async event=>{validateSender(event);try{const response=await net.fetch('https://api.github.com/repos/alexanderrippke-create/montagebericht-app/releases/latest',{headers:{Accept:'application/vnd.github+json','User-Agent':'Montagebericht-Desktop'},signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('GitHub antwortet mit Status '+response.status);checkedUpdate=releaseInfo(await response.json(),app.getVersion());return checkedUpdate}catch{return {ok:false,current:app.getVersion(),message:'Updateprüfung nicht möglich. Bitte Internetverbindung prüfen oder später erneut versuchen.'}}});
ipcMain.handle('open-update',async event=>{validateSender(event);if(!checkedUpdate?.available)return {ok:false,message:'Bitte zuerst nach Updates suchen.'};try{await shell.openExternal(checkedUpdate.downloadUrl||checkedUpdate.releaseUrl);return {ok:true}}catch{return {ok:false,message:'Download konnte nicht geöffnet werden.'}}});

ipcMain.handle('open-report',async event=>{validateSender(event);const result=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'Montagebericht',extensions:['montagebericht','json']}]});if(result.canceled)return {canceled:true};try{const file=result.filePaths[0];const stat=await fs.stat(file);if(stat.size>25_000_000)throw Error('Datei zu groß');return {ok:true,path:file,data:JSON.parse(await fs.readFile(file,'utf8'))}}catch(error){return {ok:false,message:error.message}}});
ipcMain.handle('save-report',async(event,request)=>{validateSender(event);try{if(!request?.data?.report?.fields||request.data.schemaVersion!==1)throw Error('Ungültiges Berichtsformat');if(request.data.report.fields.finalizedId&&!request.data.report.archive){const pdf=await archivedPdf(request.data.report.fields.finalizedId);request.data.report.archive={pdf:pdf.toString('base64'),sha256:crypto.createHash('sha256').update(pdf).digest('hex')}}let file=request.path;if(!file){const result=await dialog.showSaveDialog(win,{defaultPath:'Montagebericht.montagebericht',filters:[{name:'Montagebericht',extensions:['montagebericht']}]});if(result.canceled)return {canceled:true};file=result.filePath}const temporary=file+'.'+crypto.randomUUID()+'.tmp';try{await fs.writeFile(temporary,JSON.stringify(request.data,null,2),{flag:'wx'});await fs.rename(temporary,file)}finally{await fs.rm(temporary,{force:true}).catch(()=>{})}return {ok:true,path:file}}catch(error){return {ok:false,message:'Bericht konnte nicht gespeichert werden: '+error.message}}});
