'use strict';
const form=document.querySelector('#report'),times=document.querySelector('#times'),parts=document.querySelector('#parts'),canvas=document.querySelector('#signature'),ctx=canvas.getContext('2d');
const OFFICE_EMAIL='alexander.rippke@gustav-schmidt.de';
const storageKey=reportDepartment==='karcher'?'montagebericht.karcher.entwurf.v1':'montagebericht.entwurf.v1';let signed=false,drawing=false,last=null;
const today=new Intl.DateTimeFormat('sv-SE').format(new Date());
form.elements.date.value=today;form.elements.confirmedDate.value=today;
function message(text){const el=document.querySelector('#feedback');el.textContent=text;el.style.display='block';clearTimeout(message.timer);message.timer=setTimeout(()=>el.style.display='none',6000)}
const partFields=reportDepartment==='karcher'?[['quantity','number'],['articleNumber','text'],['description','text']]:[['quantity','number'],['description','text']];
const timeFields=reportDepartment==='karcher'?[['date','date'],['from','time'],['to','time'],['pause','number'],['hours','number']]:[['date','date'],['from','time'],['to','time'],['pause','number'],['hours','number'],['km','number'],['normal','number'],['p25','number'],['p50','number'],['p70','number'],['note','text']];
function addRow(target,fields,data={}){const tr=document.createElement('tr');for(const [key,type] of fields){const td=document.createElement('td'),input=document.createElement('input');input.type=type;input.dataset.key=key;input.setAttribute('aria-label',({date:'Datum',from:'Von',to:'Bis',pause:'Pause in Minuten',hours:'Stunden inklusive Anfahrt',normal:'Normalstunden',p25:'25 Prozent',p50:'50 Prozent',p70:'70 Prozent',note:'Bemerkungen',quantity:'Menge',articleNumber:'Artikelnummer',description:'Ersatzteil'})[key]||key);if(type==='number'){input.min='0';input.step=key==='km'?'1':'0.01'}input.value=data[key]??(key==='date'?form.elements.date.value:'');td.append(input);tr.append(td)}const td=document.createElement('td');td.className='noprint';const b=document.createElement('button');b.type='button';b.className='remove';b.textContent='×';b.setAttribute('aria-label','Zeile entfernen');b.onclick=()=>{tr.remove();update()};td.append(b);tr.append(td);target.append(tr);update()}
function rows(target){return [...target.rows].map(tr=>Object.fromEntries([...tr.querySelectorAll('input')].map(i=>[i.dataset.key,i.value])))}
function isCompressorMaintenance(fields){return /(?:kompressor[\s-]*wartung|wartung[\s-]*(?:am\s+|des\s+)?kompressor)/i.test((fields.task||'')+' ' +(fields.work||''))}
function update(){document.querySelector('#compressorMaintenance').hidden=!(reportDepartment==='montage'&&isCompressorMaintenance({task:form.elements.task.value,work:form.elements.work.value}));const values=rows(times);document.querySelector('#hoursTotal').textContent=values.reduce((s,r)=>s+(Number(r.hours)||0),0).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2});document.querySelector('#kmTotal').textContent=values.reduce((s,r)=>s+(Number(r.km)||0),0).toLocaleString('de-DE');const receivers=[OFFICE_EMAIL,form.elements.email.value].filter(Boolean);document.querySelector('#recipients').textContent=receivers.length?'Vorgesehene Empfänger: '+receivers.join(' · '):'Empfänger werden aus den E-Mail-Feldern übernommen.'}
function snapshot(){const fields={office:OFFICE_EMAIL};for(const el of form.elements){if(!el.name)continue;if(el.name==='serviceKinds'){if(!fields.serviceKinds)fields.serviceKinds=[];if(el.checked)fields.serviceKinds.push(el.value);continue}if(el.type==='radio'){if(el.checked)fields[el.name]=el.value}else fields[el.name]=el.type==='checkbox'?el.checked:el.value}return {fields,times:rows(times),parts:rows(parts),signature:signed?canvas.toDataURL():null}}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(snapshot()));message('Entwurf auf diesem Gerät gespeichert.')}catch{message('Speichern im Browser nicht möglich. Bitte den Bericht als PDF sichern.')}}
let restoreGeneration=0;function restore(data){const generation=++restoreGeneration;ctx.clearRect(0,0,canvas.width,canvas.height);signed=false;for(const el of form.elements){if(el.name==='serviceKinds'){const selected=Array.isArray(data.fields.serviceKinds)?data.fields.serviceKinds:[data.fields.kind||'Reparatur'];el.checked=selected.includes(el.value);continue}if(!el.name||!(el.name in data.fields))continue;const val=data.fields[el.name];if(el.type==='radio')el.checked=el.value===val;else if(el.type==='checkbox')el.checked=!!val;else el.value=val}times.replaceChildren();parts.replaceChildren();for(const r of data.times||[])addRow(times,timeFields,r);for(const r of data.parts||[])addRow(parts,partFields,r);if(data.signature){const img=new Image();img.onload=()=>{if(generation!==restoreGeneration)return;ctx.drawImage(img,0,0,canvas.width,canvas.height);signed=true};img.src=data.signature}update()}
document.querySelector('#addTime').onclick=()=>addRow(times,timeFields);
document.querySelector('#addPart').onclick=()=>addRow(parts,partFields);
document.querySelector('#save').onclick=save;form.addEventListener('submit',e=>e.preventDefault());form.addEventListener('input',e=>{const input=e.target;if(['from','to','pause'].includes(input.dataset.key)){const row=input.closest('tr'),get=k=>row.querySelector('[data-key="'+k+'"]');const from=get('from').value,to=get('to').value;if(from&&to){const minutes=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};let duration=minutes(to)-minutes(from);if(duration<0)duration+=1440;const pause=Number(get('pause').value)||0;if(pause>duration){get('hours').value='';message('Die Pause darf nicht länger als die angegebene Arbeitszeit sein.')}else get('hours').value=((duration-pause)/60).toFixed(2)}else get('hours').value=''}if(reportDepartment==='montage'&&['from','to','pause','hours','date'].includes(input.dataset.key)){const row=input.closest('tr'),get=k=>row.querySelector('[data-key="'+k+'"]');const day=get('date').value?new Date(get('date').value+'T12:00:00').getDay():null;const hours=Number(get('hours').value)||0;if(day!==null&&day!==0){const normal=day===6?0:Math.min(hours,8),p25=Math.min(Math.max(hours-normal,0),2),p50=Math.max(hours-normal-p25,0);for(const [k,v] of Object.entries({normal,p25,p50,p70:0}))get(k).value=v?v.toFixed(2):''}}update()});
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);drawing=true;last=point(e);signed=true;ctx.fillStyle='#153751';ctx.beginPath();ctx.arc(last.x,last.y,2,0,Math.PI*2);ctx.fill()});canvas.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e);ctx.strokeStyle='#153751';ctx.lineWidth=3;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p});for(const evt of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(evt,()=>drawing=false);
document.querySelector('#clearSignature').onclick=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);signed=false};
document.querySelector('#check').onclick=()=>{if(!form.reportValidity())return;const missing=[];if(!form.elements.order.value)missing.push('Auftragsnummer');if(!form.elements.technician.value)missing.push('Monteur');if(!form.elements.work.value)missing.push('ausgeführte Arbeiten');if(!rows(times).some(r=>Number(r.hours)>0))missing.push('Arbeitsstunden');if(!form.elements.email.value)missing.push('Kunden-E-Mail');if(!signed)missing.push('Unterschrift');message(missing.length?'Bitte ergänzen: '+missing.join(', '):'Bericht vollständig. Du kannst ihn als PDF speichern. E-Mail-Versand ist noch nicht verbunden.')};
function preparePrint(){
 if(reportDepartment==='karcher'){prepareKarcherPrint();return}
 let paper=document.querySelector('#printReport');if(!paper){paper=document.createElement('article');paper.id='printReport';document.body.append(paper)}paper.replaceChildren();
 const data=snapshot(),f=data.fields;
 const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el};
 const date=value=>{if(!value)return '';const [y,m,d]=value.split('-');return d+'.'+m+'.'+y};
 const header=node('header',undefined,'paper-header'),logo=node('img');logo.src='company-logo.png';logo.alt='Gustav Schmidt';header.append(logo,node('h1','Montagebericht / Arbeitsnachweis'));paper.append(header);
 const customer=node('div',undefined,'paper-fields');
 for(const [key,label] of [['customer','Firma / Kunde'],['technician','Monteur'],['street','Straße'],['order','Auftragsnummer'],['city','PLZ / Ort'],['orderedBy','Bestellung durch'],['phone','Telefon'],['purchase','Bestellnummer'],['email','Kunden-E-Mail'],['purchaseDate','Bestelldatum'],['date','Einsatzdatum']]){const field=node('div',undefined,'paper-field');field.append(node('span',label),node('div',key.toLowerCase().includes('date')?date(f[key]):f[key]||'\u00a0'));customer.append(field)}paper.append(customer);
 const machines=node('div',undefined,'paper-fields');for(const [key,label] of [['machine','Anlage / Maschine / Antrieb'],['power','Leistung'],['machineId','Typ / Teile-Nr. / Fabr.-Nr. / Inv.-Nr.'],['year','Baujahr']]){const field=node('div',undefined,'paper-field');field.append(node('span',label),node('div',f[key]||'\u00a0'));machines.append(field)}paper.append(machines);
 paper.append(node('p','Art des Einsatzes: '+(f.kind||'Montage'),'paper-kind'));
 function textBlock(title,text){const block=node('section',undefined,'paper-block');block.append(node('h2',title),node('div',text||'\u00a0','paper-text'));paper.append(block)}
 if(f.task)textBlock('Aufgabe aus dem Termin',f.task);
 if(isCompressorMaintenance(f))textBlock('Kompressorwartung',[['Betriebsstunden',f.compressorHours],['Laststunden',f.compressorLoadHours],['Nächste Wartung voraussichtlich am',date(f.compressorNextDate)],['Nächste Wartung bei Betriebsstunden',f.compressorNextHours]].map(([label,value])=>label+': '+(value||'–')).join('\n'));
 const workRows=data.times.filter(r=>Object.values(r).some(Boolean));
 function table(title,headings,records,keys){const block=node('section',undefined,'paper-block');block.append(node('h2',title));const table=node('table'),thead=node('thead'),hr=node('tr');for(const h of headings)hr.append(node('th',h));thead.append(hr);table.append(thead);const tbody=node('tbody');for(const r of records){const tr=node('tr');for(const key of keys)tr.append(node('td',key==='date'?date(r[key]):r[key]||'\u00a0'));tbody.append(tr)}table.append(tbody);block.append(table);paper.append(block)}
 table('Arbeitszeiten',['Datum','Von','Bis','Pause Min.','Std. inkl. Anfahrt','km','N','25 %','50 %','70 %','Bemerkungen'],workRows,timeFields.map(([k])=>k));
 paper.append(node('p','Gesamtstunden: '+document.querySelector('#hoursTotal').textContent+'     Kilometer: '+document.querySelector('#kmTotal').textContent,'paper-totals'));
 textBlock('Ausgeführte Arbeiten',f.work);
 const materials=data.parts.filter(r=>r.quantity||r.description);const paired=[];const half=Math.ceil(materials.length/2);for(let i=0;i<half;i++)paired.push({quantity:materials[i].quantity,description:materials[i].description,quantity2:materials[i+half]?.quantity,description2:materials[i+half]?.description});table('Material / zu berechnende Ersatzteile',['Menge','Bezeichnung','Menge','Bezeichnung'],paired.length?paired:[{}],['quantity','description','quantity2','description2']);
 const confirmation=node('section',undefined,'paper-block paper-confirmation');confirmation.append(node('h2','Kundenbestätigung'));const checks=node('div',undefined,'paper-checks');for(const [key,label] of [['machineOk','Maschinen / Anlagen in Ordnung'],['workOk','Arbeiten ordnungsgemäß ausgeführt'],['paid','Gegen Bezahlung']])checks.append(node('span',(f[key]?'☑ ':'☐ ')+label));confirmation.append(checks);const signature=node('div',undefined,'paper-signature');signature.append(node('div','Datum: '+date(f.confirmedDate)+'\nName: '+(f.signer||'')));const signatureBox=node('div');if(signed){const img=node('img');img.src=data.signature;img.alt='Unterschrift Kunde';signatureBox.append(img)}signatureBox.append(node('div','Unterschrift Kunde','signature-label'));signature.append(signatureBox);confirmation.append(signature,node('p','Dieser Arbeitsnachweis dient als Grundlage für die Abrechnung der eingetragenen Tätigkeit.','paper-legal'));paper.append(confirmation);
 paper.append(node('footer','Gustav Schmidt · www.gustav-schmidt.de','paper-footer'));
}
document.querySelector('#print').onclick=()=>{preparePrint();window.print()};window.addEventListener('beforeprint',preparePrint);
try{const saved=localStorage.getItem(storageKey);if(saved)restore(JSON.parse(saved));else{addRow(times,timeFields);addRow(parts,partFields)}}catch{addRow(times,timeFields);addRow(parts,partFields);message('Gespeicherter Entwurf konnte nicht geladen werden.')}
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'read_montagebericht',title:'Montagebericht lesen',description:'Liest den aktuellen Bericht einschließlich Arbeitszeiten und Material. Speichert und versendet nichts.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Ein leeres Objekt wird erwartet.');const data=snapshot();delete data.signature;return {...data,signed,emailConnected:false}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}


