'use strict';
(()=>{
 const statement='Mit meiner Unterschrift bestätige ich die im Bericht eingetragenen Arbeitszeiten, ausgeführten Arbeiten und Materialien sowie die von mir angekreuzten Angaben.';
 const section=canvas.closest('section');
 const label=document.createElement('label');label.className='hint';const accepted=document.createElement('input');accepted.type='checkbox';accepted.name='signatureAccepted';try{accepted.checked=!!JSON.parse(localStorage.getItem(storageKey)||'null')?.fields.signatureAccepted}catch{};label.append(accepted,document.createTextNode(' '+statement));section.insertBefore(label,canvas);
 const status=document.createElement('p');status.className='hint';status.setAttribute('role','status');section.append(status);
 const finish=document.createElement('button');finish.type='button';finish.className='primary';finish.textContent='Unterschriebenen Bericht abschließen';section.append(finish);
 const reopen=document.createElement('button');reopen.type='button';reopen.textContent='Neue Bearbeitung – erneut unterschreiben';reopen.hidden=true;section.append(reopen);
 const originalSnapshot=snapshot,originalPrint=preparePrint;
 let completion=null,locked=null;
 try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved?.fields.finalizedId){completion={id:saved.fields.finalizedId,at:saved.fields.signedAt};locked=saved}}catch{}
 snapshot=function(){if(locked)return structuredClone(locked);const data=originalSnapshot();if(completion){data.fields.finalizedId=completion.id;data.fields.signedAt=completion.at}return data};
 preparePrint=function(){originalPrint();const data=snapshot();const block=document.querySelector('.paper-confirmation');const detail=document.createElement('p');detail.className='paper-legal';detail.textContent=(data.fields.signedAt?'Abgeschlossen am '+new Date(data.fields.signedAt).toLocaleString('de-DE')+' (Gerätezeit)':'Entwurf – noch nicht abgeschlossen');block.append(detail);if(data.fields.signatureAccepted){const text=document.createElement('p');text.className='paper-legal';text.textContent=statement;block.append(text)}if(data.fields.finalizedId){const id=document.createElement('p');id.className='paper-legal';id.textContent='Bericht-ID: '+data.fields.finalizedId;block.append(id)}};
 window.removeEventListener('beforeprint',originalPrint);window.addEventListener('beforeprint',preparePrint);
 function setLocked(value){document.querySelectorAll('main input, main textarea, main select, main button').forEach(el=>{if(el===reopen||el.id==='print'||el.id==='save'||el.closest('.delivery')||el.closest('.office-settings')||el.closest('.reset-controls')||el.closest('.department-switch')||el.closest('.report-tabs'))return;el.disabled=value});canvas.style.pointerEvents=value?'none':'';const techCanvas=document.querySelector('#technicianSignature');if(techCanvas)techCanvas.style.pointerEvents=value?'none':'';reopen.hidden=!value;finish.hidden=value;status.textContent=value?'Bericht abgeschlossen am '+new Date(completion.at).toLocaleString('de-DE')+'. PDF und Nachweis liegen unter Dokumente / Montageberichte / Abgeschlossen. Änderungen erfordern eine neue Unterschrift.':'Vor dem Unterschreiben den vollständigen Bericht prüfen. Beim Abschluss wird die unterschriebene Fassung lokal archiviert.'}
 finish.onclick=async()=>{if(!form.reportValidity())return;const f=originalSnapshot().fields;const missing=[];for(const [key,title] of [['order','Auftragsnummer'],['technician','Monteur'],['work','ausgeführte Arbeiten'],['signer','Name']])if(!f[key]?.trim())missing.push(title);if(!rows(times).some(r=>Number(r.hours)>0))missing.push('Arbeitsstunden');if(reportDepartment==='karcher'&&!f.technicianSignatureData)missing.push('Unterschrift Monteur');if(!signed)missing.push('Unterschrift Kunde');if(!accepted.checked)missing.push('Bestätigung');if(missing.length){message('Bitte ergänzen: '+missing.join(', '));return}finish.disabled=true;window.reportBusy=true;completion={id:crypto.randomUUID(),at:new Date().toISOString()};setLocked(true);try{const result=await desktopReport.finalize();if(!result.ok)throw Error(result.message);locked=originalSnapshot();locked.fields.finalizedId=completion.id;locked.fields.signedAt=completion.at;localStorage.setItem(storageKey,JSON.stringify(locked));message('Bericht abgeschlossen und unterschriebene PDF archiviert.')}catch(error){completion=null;locked=null;setLocked(false);message(error.message)}finally{finish.disabled=false;window.reportBusy=false;window.dispatchEvent(new Event('reportchanged'))}};
 reopen.onclick=()=>{locked=null;completion=null;const techCanvas=document.querySelector('#technicianSignature');if(techCanvas){techCanvas.getContext('2d').clearRect(0,0,techCanvas.width,techCanvas.height);form.elements.technicianSignatureData.value=''}ctx.clearRect(0,0,canvas.width,canvas.height);signed=false;accepted.checked=false;setLocked(false);localStorage.setItem(storageKey,JSON.stringify(snapshot()));message('Neue Bearbeitung begonnen. Die vorherige unterschriebene PDF bleibt im Archiv. Bitte erneut unterschreiben.')};
 setLocked(!!locked);
})();
