'use strict';
window.reportDepartment=localStorage.getItem('montagebericht.department')==='karcher'?'karcher':'montage';
window.reportCalendar=reportDepartment==='karcher'?'Iris Illian':'Kalender';
(()=>{const bar=document.createElement('nav');bar.className='department-switch noprint';bar.setAttribute('aria-label','Abteilung');for(const [value,title]of [['montage','Montagebericht'],['karcher','Kärcher-Service']]){const button=document.createElement('button');button.type='button';button.textContent=title;button.setAttribute('aria-pressed',String(reportDepartment===value));button.className=reportDepartment===value?'primary':'';button.onclick=()=>{if(value===reportDepartment)return;try{localStorage.setItem(storageKey,JSON.stringify(snapshot()));localStorage.setItem('montagebericht.department',value);window.desktopReport?desktopReport.reloadReport():location.reload()}catch{message('Abteilung konnte nicht gewechselt werden. Bitte den Bericht sichern.')}};bar.append(button)}document.querySelector('main').prepend(bar);if(reportDepartment!=='karcher')return;
 document.title='Kärcher-Service · Gustav Schmidt';document.querySelector('h1').textContent='Kärcher-Servicebericht';document.querySelector('.brand-subtitle').textContent='Kärcher Center Gustav Schmidt';document.querySelector('.eyebrow').textContent='KÄRCHER SERVICE';document.querySelector('.muted').textContent='Reparatur, Wartung und Prüfung von Kärcher-Geräten.';
 const form=document.querySelector('#report');for(const name of ['orderedBy','purchase','purchaseDate','power'])form.elements[name].closest('label').hidden=true;
 function field(name,title,type='text'){const label=document.createElement('label');label.textContent=title;const input=document.createElement(type==='textarea'?'textarea':'input');input.name=name;if(type!=='textarea')input.type=type;else input.rows=3;label.append(input);return label}
 form.querySelector('.grid').append(field('customerNumber','Kunden-Nr.'));const device=form.elements.machine.closest('section');device.querySelector('h2').textContent='Gerät & Arbeitsbericht';form.elements.machine.closest('label').firstChild.textContent='Gerätetyp';form.elements.machineId.closest('label').firstChild.textContent='Geräte- / Seriennummer';device.querySelector('.grid').append(field('accessories','Zubehör'),field('defects','Voraussichtliche Mängel','textarea'));
 const fieldset=device.querySelector('fieldset');fieldset.replaceChildren();const legend=document.createElement('legend');legend.textContent='Serviceart';fieldset.append(legend);for(const [i,value]of ['Reparatur','Wartung','UVV-/VDE-Prüfung','Kostenvoranschlag'].entries()){const label=document.createElement('label');const radio=document.createElement('input');radio.type='checkbox';radio.name='serviceKinds';radio.value=value;radio.checked=i===0;label.append(radio,document.createTextNode(' '+value));fieldset.append(label)}
 const timeSection=document.querySelector('#times').closest('section');timeSection.querySelector('.hint').textContent='Arbeitsstunden werden aus Von/Bis abzüglich Pause berechnet und können korrigiert werden.';document.querySelector('#addTime').textContent='+ Arbeitszeit';timeSection.querySelector('thead tr').innerHTML='<th>Datum</th><th>Von</th><th>Bis</th><th>Pause Min.</th><th>Stunden</th><th class="noprint"></th>';document.querySelector('#kmTotal').parentElement.hidden=true;
 const headings=document.querySelector('#parts').closest('table').querySelector('thead tr');const article=document.createElement('th');article.textContent='Artikelnummer';headings.insertBefore(article,headings.children[1]);
 const signSection=document.querySelector('#signature').closest('section');const tech=document.createElement('div');tech.innerHTML='<div class="signaturehead"><label for="technicianSignature">Unterschrift Monteur</label><button type="button" id="clearTechnicianSignature">Unterschrift löschen</button></div><canvas id="technicianSignature" width="1000" height="220" aria-label="Unterschrift Monteur"></canvas><input type="hidden" name="technicianSignatureData">';signSection.insertBefore(tech,signSection.querySelector('.signaturehead'));
})();
