'use strict';
(()=>{const pane=document.createElement('section');pane.className='import-panel noprint';pane.innerHTML=`<div class="sectionhead"><h2>Termin übernehmen</h2></div><p class="hint">Termine aus dem Outlook-Kalender übernehmen oder die Terminnotiz einfügen. Firma und Adresse können auch aus dem Terminort kommen, z. B. „Musterfirma, Hauptstraße 12, 12345 Berlin“. Angaben in der Beschreibung haben Vorrang. Der Import erfolgt auf diesem Gerät.</p><div class="grid"><div><label for="outlookText">Text aus Outlook</label><textarea id="outlookText" rows="5" placeholder="Kunde: Musterfirma&#10;Auftrag: 123456&#10;Kunden-E-Mail: kunde@firma.de&#10;Arbeiten: Rohrleitung erneuern"></textarea><button type="button" id="readText">Text auswerten</button></div></div><div id="importPreview" hidden><h3>Angaben prüfen</h3><p class="hint">Erkennung bitte prüfen und fehlende Angaben ergänzen. Nur ausgefüllte Felder werden übernommen. Gleichnamige Angaben im Bericht werden dabei ersetzt.</p><div class="grid"><label>Kunde<input id="importCustomer"></label><label>Auftragsnummer<input id="importOrder"></label><label>Kunden-E-Mail<input id="importEmail" type="email"></label><label>Sachbearbeiter<input id="importOfficeContact" placeholder="Name aus den Sachbearbeitern"></label><label>Einsatzdatum<input id="importDate" type="date"></label><label>Straße<input id="importStreet"></label><label>PLZ / Ort<input id="importCity"></label><label>Telefon<input id="importPhone" type="tel"></label><label>Maschine / Anlage<input id="importMachine"></label><label class="wide">Aufgabenbeschreibung<textarea id="importTask" rows="3"></textarea></label></div><div class="import-actions"><button type="button" id="cancelImport">Abbrechen</button><button type="button" class="primary" id="applyImport">In Bericht übernehmen</button></div></div><p id="importStatus" role="status" aria-live="polite"></p>`;
 document.querySelector('#report').before(pane);const mapping={customer:'importCustomer',order:'importOrder',email:'importEmail',date:'importDate',task:'importTask',street:'importStreet',city:'importCity',phone:'importPhone',machine:'importMachine',officeContact:'importOfficeContact'};const get=id=>document.getElementById(id);const status=text=>get('importStatus').textContent=text;
 function preview(data){for(const [key,id]of Object.entries(mapping))get(id).value=data[key]||'';get('importPreview').hidden=false;status('Angaben erkannt. Bitte prüfen und übernehmen.');get('importCustomer').focus()}
 get('readText').onclick=()=>{const text=get('outlookText').value;if(!text.trim()){status('Bitte zuerst den Text aus Outlook einfügen.');return}preview(ReportImport.parseText(text));};
 get('cancelImport').onclick=()=>{get('importPreview').hidden=true;status('Übernahme abgebrochen. Der Bericht wurde nicht geändert.')};
 get('applyImport').onclick=()=>{if(!get('importEmail').reportValidity()||!get('importDate').reportValidity())return;let count=0;const incomingCustomer=get('importCustomer').value.trim();if(incomingCustomer&&incomingCustomer!==form.elements.customer.value.trim()&&!get('importEmail').value.trim())form.elements.email.value='';const oldDate=form.elements.date.value;for(const [key,id]of Object.entries(mapping)){const value=get(id).value.trim();if(value||key==='officeContact'){form.elements[key].value=value;if(value)count++}}if(!count){status('Bitte mindestens eine Angabe ergänzen.');return}if(form.elements.date.value!==oldDate){for(const row of times.rows){const inputs=[...row.querySelectorAll('input')];if(inputs.filter(el=>el.dataset.key!=='date').every(el=>!el.value)){row.querySelector('[data-key="date"]').value=form.elements.date.value}}}update();get('importPreview').hidden=true;status(count+' Angaben in den Bericht übernommen. Entwurf bitte speichern.');form.elements.customer.focus()};
})();


