'use strict';
function prepareKarcherPrint(){
 let paper=document.querySelector('#printReport');if(!paper){paper=document.createElement('article');paper.id='printReport';document.body.append(paper)}paper.replaceChildren();paper.className='karcher-paper';const data=snapshot(),f=data.fields;const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el};const date=v=>v?v.split('-').reverse().join('.'):'';
 const header=node('header',undefined,'paper-header');const brand=node('div',undefined,'karcher-brand');brand.append(node('strong','KÄRCHER'),node('div','KÄRCHER CENTER'),node('div','GUSTAV SCHMIDT'));header.append(brand,node('h1','SERVICEBERICHT'));paper.append(header,node('p','Serviceart: '+(Array.isArray(f.serviceKinds)?(f.serviceKinds.join(' · ')||'Keine Auswahl'):(f.kind||'Reparatur')),'paper-kind'));
 const fields=node('div',undefined,'paper-fields');for(const [key,label]of [['customer','Firma / Name'],['machine','Gerätetyp'],['street','Straße'],['year','Baujahr'],['city','PLZ / Ort'],['machineId','Geräte- / Seriennummer'],['phone','Telefon'],['accessories','Zubehör'],['email','E-Mail'],['defects','Voraussichtliche Mängel'],['customerNumber','Kunden-Nr.'],['order','Auftragsnummer'],['technician','Monteur'],['date','Einsatzdatum']]){const field=node('div',undefined,'paper-field');field.append(node('span',label),node('div',key==='date'?date(f[key]):f[key]||' '));fields.append(field)}paper.append(fields);
 function table(title,headings,records,keys){const section=node('section',undefined,'paper-block');section.append(node('h2',title));const table=node('table');const head=node('thead'),tr=node('tr');headings.forEach(h=>tr.append(node('th',h)));head.append(tr);table.append(head);const body=node('tbody');for(const r of records.length?records:[{}]){const row=node('tr');for(const key of keys)row.append(node('td',key==='date'?date(r[key]):r[key]||' '));body.append(row)}table.append(body);section.append(table);paper.append(section)}
 table('ARBEITSZEIT',['Datum','Von','Bis','Pause Min.','Stunden'],data.times,['date','from','to','pause','hours']);paper.append(node('p','Gesamtstunden: '+document.querySelector('#hoursTotal').textContent,'paper-totals'));
 function block(title,text){const section=node('section',undefined,'paper-block');section.append(node('h2',title),node('div',text||' ','paper-text'));paper.append(section)}if(f.task)block('Aufgabe aus dem Termin',f.task);block('ARBEITSBERICHT',f.work);table('ERSATZTEILE',['Menge','Artikelnummer','Bezeichnung der zu berechnenden Ersatzteile'],data.parts.filter(r=>r.quantity||r.articleNumber||r.description),['quantity','articleNumber','description']);
 const confirmation=node('section',undefined,'paper-block paper-confirmation');confirmation.append(node('h2','Bestätigung'),node('p','Datum: '+date(f.confirmedDate)));const signatures=node('div',undefined,'paper-signature');for(const [title,signature,name]of [['Unterschrift Monteur',f.technicianSignatureData,f.technician],['Unterschrift Kunde',data.signature,f.signer]]){const box=node('div');box.append(node('div',name||' '));if(signature){const img=node('img');img.src=signature;img.alt=title;box.append(img)}box.append(node('div',title,'signature-label'));signatures.append(box)}confirmation.append(signatures);paper.append(confirmation,node('footer','Gustav Schmidt GmbH & Co. KG · info@gustav-schmidt.de · kaercher.gustav-schmidt.de/service','paper-footer'));
}
(()=>{if(reportDepartment!=='karcher')return;const techCanvas=document.querySelector('#technicianSignature'),techCtx=techCanvas.getContext('2d'),field=form.elements.technicianSignatureData;let active=false,lastPoint=null;const point=e=>{const r=techCanvas.getBoundingClientRect();return {x:(e.clientX-r.left)*techCanvas.width/r.width,y:(e.clientY-r.top)*techCanvas.height/r.height}};function capture(){field.value=techCanvas.toDataURL();field.dispatchEvent(new Event('input',{bubbles:true}))}techCanvas.addEventListener('pointerdown',e=>{e.preventDefault();techCanvas.setPointerCapture(e.pointerId);active=true;lastPoint=point(e);techCtx.fillStyle='#153751';techCtx.beginPath();techCtx.arc(lastPoint.x,lastPoint.y,2,0,Math.PI*2);techCtx.fill();capture()});techCanvas.addEventListener('pointermove',e=>{if(!active)return;const p=point(e);techCtx.strokeStyle='#153751';techCtx.lineWidth=3;techCtx.lineCap='round';techCtx.beginPath();techCtx.moveTo(lastPoint.x,lastPoint.y);techCtx.lineTo(p.x,p.y);techCtx.stroke();lastPoint=p;capture()});for(const event of ['pointerup','pointercancel','lostpointercapture'])techCanvas.addEventListener(event,()=>active=false);document.querySelector('#clearTechnicianSignature').onclick=()=>{techCtx.clearRect(0,0,techCanvas.width,techCanvas.height);field.value='';field.dispatchEvent(new Event('input',{bubbles:true}))};if(field.value){const img=new Image();img.onload=()=>techCtx.drawImage(img,0,0);img.src=field.value}
})();
