'use strict';
window.addEventListener('load',()=>{
 const key='montagebericht.workspace.v1';let state;let switching=false;
 const draftKey=department=>department==='karcher'?'montagebericht.karcher.entwurf.v1':'montagebericht.entwurf.v1';
 const blank=()=>{const d=structuredClone(snapshot());for(const k of Object.keys(d.fields))d.fields[k]=typeof d.fields[k]==='boolean'?false:Array.isArray(d.fields[k])?[]:'';d.fields.date=today;d.fields.confirmedDate=today;d.times=[{date:today}];d.parts=[{}];d.signature=null;return d};
 try{state=JSON.parse(localStorage.getItem(key)||'null');if(state&&(!Array.isArray(state.tabs)||!state.tabs.length))throw Error('Ungültige Sitzung')}catch{message('Sitzung konnte nicht geladen werden. Bestehende Entwürfe bleiben erhalten.');return}
 if(!state){const data=snapshot();state={active:crypto.randomUUID(),tabs:[]};state.tabs.push({id:state.active,department:reportDepartment,data,baseline:JSON.stringify(data),path:null})}
 let current=state.tabs.find(t=>t.id===state.active);if(!current)return;
 const baseSnapshot=snapshot;snapshot=function(){const data=baseSnapshot();if(current.data.iosReport)data.iosReport=current.data.iosReport;if(data.fields.finalizedId&&current.data.archive)data.archive=current.data.archive;return data};
 const bar=document.createElement('nav');bar.className='report-tabs noprint';bar.setAttribute('aria-label','Geöffnete Berichte');document.querySelector('main').prepend(bar);
 function capture(){current.data=snapshot();current.department=reportDepartment}
 function persist(){if(switching)return;capture();localStorage.setItem(key,JSON.stringify(state));localStorage.setItem(storageKey,JSON.stringify(current.data))}
 function dirty(tab){return JSON.stringify(tab.data)!==tab.baseline}
 function button(text,action){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=action;return b}
 function activate(tab){try{persist();localStorage.setItem(draftKey(tab.department),JSON.stringify(tab.data));localStorage.setItem('montagebericht.department',tab.department);state.active=tab.id;localStorage.setItem(key,JSON.stringify(state));switching=true;desktopReport.reloadReport()}catch(e){message('Berichtswechsel fehlgeschlagen: '+e.message)}}
 async function saveFile(as=false){capture();const data=structuredClone(current.data);const result=await desktopReport.saveReport({path:as?null:current.path,data:{format:'montagebericht',schemaVersion:1,department:current.department,report:data}});if(result.ok){current.path=result.path;current.baseline=JSON.stringify(data);persist();draw();message('Berichtsdatei gespeichert.')}else if(!result.canceled)message(result.message);return !!result.ok}
 async function close(tab){capture();if(dirty(tab)){const saveFirst=confirm('Ungespeicherte Änderungen vor dem Schließen speichern?');if(saveFirst){if(tab!==current){activate(tab);return}if(!await saveFile())return}else if(!confirm('Änderungen wirklich verwerfen und Tab schließen?'))return}state.tabs=state.tabs.filter(t=>t.id!==tab.id);if(!state.tabs.length){const data=blank();state.tabs.push({id:crypto.randomUUID(),department:reportDepartment,data,baseline:JSON.stringify(data),path:null})}if(tab===current)activate(state.tabs[0]);else{persist();draw()}}
 function draw(){bar.replaceChildren();for(const tab of state.tabs){const label=(tab.data.fields.customer||'Neuer Bericht')+(dirty(tab)?' *':'');const b=button(label,()=>{if(tab!==current)activate(tab)});b.setAttribute('aria-pressed',String(tab===current));bar.append(b,button('×',()=>close(tab)))}bar.append(button('+',()=>{const data=blank();const tab={id:crypto.randomUUID(),department:reportDepartment,data,baseline:JSON.stringify(data),path:null};state.tabs.push(tab);activate(tab)}),button('Bericht öffnen',async()=>{const r=await desktopReport.openReport();if(!r.ok){if(!r.canceled)message(r.message);return}try{let data=r.data;let department=reportDepartment;if(data.format==='montagebericht'){if(data.schemaVersion!==1)throw Error('Unbekannte Dateiversion');department=data.department;data=data.report}if(!['montage','karcher'].includes(department)||!data?.fields||!Array.isArray(data.times)||!Array.isArray(data.parts))throw Error('Ungültige Berichtsdatei');const existing=state.tabs.find(t=>t.path===r.path);if(existing){activate(existing);return}const tab={id:crypto.randomUUID(),department,data,baseline:JSON.stringify(data),path:r.path};state.tabs.push(tab);activate(tab)}catch(e){message(e.message)}}),button('Speichern unter',()=>saveFile(true)))}
 document.querySelector('#save').textContent='Bericht speichern';document.querySelector('#save').onclick=()=>saveFile();
 let timer;document.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{try{persist();draw()}catch(e){message('Sitzung konnte nicht gesichert werden: '+e.message)}},250)});document.addEventListener('click',()=>setTimeout(()=>{try{persist();draw()}catch(e){message(e.message)}},0));
 window.addEventListener('beforeunload',e=>{try{persist()}catch{}if(!switching&&state.tabs.some(dirty)){e.preventDefault();e.returnValue='Ungespeicherte Berichte'}});
 document.querySelectorAll('.department-switch button').forEach((b,i)=>{b.onclick=()=>{const department=i?'karcher':'montage';if(department===reportDepartment)return;const existing=state.tabs.find(t=>t.department===department);if(existing){activate(existing);return}let data;try{data=JSON.parse(localStorage.getItem(draftKey(department))||'null')}catch{}data=data||blank();const tab={id:crypto.randomUUID(),department,data,baseline:JSON.stringify(data),path:null};state.tabs.push(tab);activate(tab)}});
 const reset=document.querySelector('#resetReport');if(reset)reset.onclick=()=>bar.querySelectorAll('button')[state.tabs.length*2].click();
 draw();
});

